### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by ExtraGravity** [enochtsang/TerminalFighter#56]
I remember we talked about a UI design before for in game but I don't remember what it is, anyone remember? @bseto @beaesguerra @cheunggg

**Comment by bseto** [comment]
I kind of don't remember either... I remember we did not want any thick bars on the left and right of the machine. We also wanted maybe a floating bar/no bar for the typing area?

**Comment by beaesguerra** [comment]
Yeah, we were going to include a history of the previous entered words above the terminal box and I think we also talked about moving the terminal to the other side of the ship so that the typed words is right beside your player? I'm not sure if these were what we decided, but I remember discussing them. Also, there was the UI for typing certain things to show certain information somewhere on the side?

**Comment by ExtraGravity** [comment]
Yea I remember that. So "terminal will be on the bottom right. The terminal will be an opaque bar, and the typed history will be above the bar in a transparent fashion. There will be one "screen" on the bottom left which the player can choose what appears in it, whether it's enemy details or ship health details etc.
